### ISSUE TITLE
Baner Ads are not showed

### ISSUE THREAD

**Issue by Dima107** [myflashlab/Admob-ANE#57] opened 2018-12-04 10:09 UTC
## Environment ##
* Android Version: 6
* iOS Version:11.3, 12
* AIR Version: 31

## Problem Description ##
I request Horizontal Smart banner ads. On some devices(for example Samsung Tab A 2016) I receive banner with ZERO size. width = 0. height = 0. On other my device (Nexus 7 2013) I can show Ads. But sometimes I see only small part of banner: full with horizontal width with height about 1 or 2 pixels

Banner show Rate ad has gone from ~89% to 28% from october

Application is live:
Moto X3M - on android
Moto X3M free - on IOS

**Comment by myflashlab** [comment] 2018-12-05 08:35
Are you experiencing this on Android or iOS or both platforms?

**Comment by Dima107** [comment] 2018-12-05 08:40
Sometimes I don't see on IOS devices. But I'm not sure why. May be it's because of zero size. May be it's because of no fill.

I'm sure On Anroid I receive banner with zero size

**Comment by myflashlab** [comment] 2018-12-05 08:53
can you give us link to download and test the app?

**Comment by Dima107** [comment] 2018-12-05 08:57
https://play.google.com/store/apps/details?id=air.com.aceviral.motox3m

**Comment by Dima107** [comment] 2018-12-05 08:58
Do you want some special build?

**Comment by myflashlab** [comment] 2018-12-06 04:41
Before anything, that was a very good game :) we enjoyed playing it here at the office. About the Ads, we could see that it works fine :thinking:

![2018-12-06 08 37 40](https://user-images.githubusercontent.com/1692948/49561805-60a66a00-f932-11e8-8102-fd4b1537dfc7.jpg)

However, I have an idea, I think you should check for the adLoadFailed event... as you suggested, maybe it's a no fill (code 3 I think). and you would probably try to load another banner size. Maybe this one ```ApiBannerAds.BANNER```.

**Comment by Dima107** [comment] 2018-12-06 08:44
I checkout all events.
I receive ad load event. On this event trace banner.width and  banner.width. It's both equal to zero. I saw this only on one device Samsung Tab A 2016. I have only 2 devices: Nexus 7 2013 and Samsung Tab A 2016

**Comment by leossmith** [comment] 2018-12-07 09:51
I get the same on my op6t

**Comment by myflashlab** [comment] 2018-12-07 13:21
Ok, guys, there seems like Google Ads servers are facing a crises or something recently. We've had a few recent reports like yours that ads are failing to load with error code 3 (no ad fill). After checking out the [Admob forum](https://productforums.google.com/forum/#!forum/google-admob-help-forum), I noticed that MANY other people are facing the exact same problem as yours.

Take [this conversation](https://productforums.google.com/forum/#!topic/google-admob-help-forum/8oc3pebOrFw;context-place=forum/google-admob-help-forum) as an example. more than a hundred of people are reporting that their apps are failing to show apps in the past few weeks.

Another interesting topic is [this one](https://productforums.google.com/forum/#!topic/google-admob-help-forum/cjA7f29Zr0E;context-place=forum/google-admob-help-forum) where people are naming their country to see if the problem is related to a part of the world or is it global. Well, as it seems, it's global!

Anyhow, considering that this is something non-ANE related issue, I'm closing it. I think you should try contact Google directly or watch the forum. There's nothing to be done on the ANE side.

About the banner ad failing on some devices, considering that you are using the smart banner size, it means that it loads different ads which are having different dimensions. This again can fall under the same problem... no fill problem. Hopefully Google will soon fix this problem.

**Closed by myflashlab** 2018-12-07 13:21 UTC

**Comment by Dima107** [comment] 2018-12-07 14:30
I implement distriq's ane - it has no such problem like zero size

**Comment by myflashlab** [comment] 2018-12-07 15:08
@Dima107 I’ll be investigating the zero size thing and update you.

**Comment by leossmith** [comment] 2018-12-07 16:54
@Dima107 is distriqt working as should? Showing the banners properly?

**Comment by myflashlab** [comment] 2018-12-08 05:50
@Dima107 Can you confirm if you are using the latest version of the ANE? If so, please send us the .apk file while [Override logs](https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir#overrideairenabledebugger) are activated so we can investigate this more.

**Comment by myflashlab** [comment] 2018-12-08 06:08
Another question. Are you initializing the banner ads only once? or multiple times?

if multiple times, are you sure you are disposing the older ones? And when disposing the older ones, is their visibility true or false?

**Comment by leossmith** [comment] 2018-12-08 12:20
I have enabled override debugger and made you a [demo one:](https://www.dropbox.com/s/zqnvef4ct8aqfxn/admobtest.apk?dl=0)

**Comment by leossmith** [comment] 2018-12-10 10:40
Any update on this?

**Comment by myflashlab** [comment] 2018-12-10 14:22
We couldn’t duplicate the problem locally However, I’ll be sending you a demo version with more deep logs. Let me update you tomorrow. Thanks

**Comment by myflashlab** [comment] 2018-12-11 05:48
Please run this demo ANE V4.0.4 [admob.ane.zip](https://github.com/myflashlab/Admob-ANE/files/2666146/admob.ane.zip) and send us the OverrideAir logs. It's probable that the problem is fixed with this version. Yet, do send us the OverrideAir logs anyway. Thanks.

**Comment by leossmith** [comment] 2018-12-11 13:10
This one works. I am sending you the logs:

> [SWF] admobtest.swf - 3,867,146 bytes after decompression
Error while reading build.prop file:Error #3001: File or directory access denied.
width is: 1080
stage width is: 1080
com.myflashlab.air.extensions.admob(AirCommand) command: isTestVersion
com.myflashlab.air.extensions.admob(AirCommand) command: initialize
com.myflashlab.air.extensions.admob(AirCommand) initialize started...
com.myflashlab.air.extensions.admob(AirCommand) _useDoubleClickApi: false
com.myflashlab.air.extensions.admob(AirCommand) initialize finished
com.myflashlab.air.extensions.admob(AirCommand) setting layers started...
com.myflashlab.air.extensions.admob(AirCommand) setting layers finished
com.myflashlab.air.extensions.admob(AirCommand) command: initBanner
com.myflashlab.air.extensions.admob(AirCommand) initBanner started...
com.myflashlab.air.extensions.admob(AirCommand) initBanner finished, Now we are waiting for the banner real width/height
com.myflashlab.air.extensions.admob(AirCommand) command: loadBanner
com.myflashlab.air.extensions.admob(AirCommand) convertJsonToRequest begin
com.myflashlab.air.extensions.admob(AirCommand) we do NOT have NetworkExtrasBundle
com.myflashlab.air.extensions.admob(AirCommand) convertJsonToRequest end
com.myflashlab.air.extensions.admob(AirCommand) onPreDraw: 1
banner loaded
x = 0
y = 1067
banner width: 0
banner height: 0
com.myflashlab.air.extensions.admob(AirCommand) onPreDraw: 2
com.myflashlab.air.extensions.admob(AirCommand) 1080x236
measure: 1080 and 236
com.myflashlab.air.extensions.admob(AirCommand) command: setPosition
com.myflashlab.air.extensions.admob(AirCommand) setPosition x = 1.0 y = 1.0
com.myflashlab.air.extensions.admob(AirCommand) command: setPosition
com.myflashlab.air.extensions.admob(AirCommand) setPosition x = 0.0 y = 0.0
com.myflashlab.air.extensions.admob(AirCommand) command: setPosition
com.myflashlab.air.extensions.admob(AirCommand) setPosition x = 0.0 y = 0.0
com.myflashlab.air.extensions.admob(AirCommand) command: setPosition
com.myflashlab.air.extensions.admob(AirCommand) setPosition x = 0.0 y = 1067.0

**Comment by myflashlab** [comment] 2018-12-11 13:17
Thanks for confirming that and thanks for the logs. we'll release it a.s.a.p
@Dima107 are you also confirming the fix on your side?

**Comment by Dima107** [comment] 2018-12-11 14:45
We start using mediator. So we don't use this ANE in our project at this moment

**Comment by leossmith** [comment] 2018-12-13 10:42
Hey please let us know about the release date. I have to update a live app :)

**Comment by AlexUrrutia** [comment] 2018-12-13 22:52
@myflashlab could you tell us what was causing this problem? thanks!
