### ISSUE TITLE
Close button don't work on iOS

### ISSUE THREAD

**Issue by Gamezhero** [myflashlab/Admob-ANE#2] opened 2016-06-06 17:29 UTC
I see ads but can't close it.
I click but don't any actions

**Comment by Gamezhero** [comment] 2016-06-06 17:39
Do you have consloe panel? Do you hide it?

**Comment by myflashlab** [comment] 2016-06-06 17:39
Could you please give us more information on this? Like what's your device
and what's the iOS version?

On Monday, June 6, 2016, Gamezhero <notifications@github.com> wrote:

> I see ads but can't close it.
> I click but don't any actions
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/myflashlab/Admob-ANE/issues/2>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABnVFA-7nSF5TNUmoAczNf9MGzXcn5W9ks5qJFkEgaJpZM4IvINJ>
> .
>


-- 
Sent from iPhone

**Comment by Gamezhero** [comment] 2016-06-06 17:44
last iso and IPhone 6
I can touch around 70-100px from top in my app all time

**Comment by myflashlab** [comment] 2016-06-06 17:56
We don't seem to be able to reproduce the problem! Could you take a
screenshot?

On Monday, June 6, 2016, Gamezhero <notifications@github.com> wrote:

> last iso and IPhone 6
> I can touch around 70-100px from top in my app all time
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/myflashlab/Admob-ANE/issues/2#issuecomment-224032864>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABnVFOT_yVatj8hYTX9DxLDuhNcSwI1qks5qJFxhgaJpZM4IvINJ>
> .
>


-- 
Sent from iPhone

**Comment by Gamezhero** [comment] 2016-06-06 19:17
![img_2037](https://cloud.githubusercontent.com/assets/18741464/15834349/c2452f54-2c33-11e6-8437-435694614aec.PNG)
I see ads but can close it
I press home button and then return to app and ad closes automatialy and I can use my app.
But in my app I can touch of top around 100px. 

I think there invisible panel
why do you need stage for init?

**Comment by myflashlab** [comment] 2016-06-07 06:40
@Gamezhero 

1) you should not test with real Ads, clicking on real ads can cause your Admob account to be suspended, so be careful about that.

2) We are still unable to reproduce the problem. Tested like a million times! Would you please run on other devices also? does it happen on other devices too?

3) the ```Stage``` instance is used for positioning Banner ads only. (converting native dimensions to Air dimensions) It's not used in interstitial ads at all.

4) yet, please use this test .ane version and tell us if it fixes the problem? We did a blind guess :)
[admob.zip](https://github.com/myflashlab/Admob-ANE/files/301980/admob.zip)

**Comment by myflashlab** [comment] 2016-06-07 07:12
Also please try this version, This is another blind guess... [admob2.zip](https://github.com/myflashlab/Admob-ANE/files/302011/admob2.zip)

**Comment by myflashlab** [comment] 2016-06-07 08:06
Aha, I found it! That's not actually a bug, it's a mess when you are calling all the methods right after each other. In our tests, we finally managed to reproduced what you explained above if we did the following quickly after each other!

1) init a interstitial ad
2) load the interstitial 
... wait for the onAdLoaded event
3) show the interstitial ad
4) and right after calling the show() method, we called to init the banner AD!

That empty space covering the top of the Flash stage and the interstitial ad, is actually the banner Ad which is initialized but conflicted the UIViews when quickly called with the show() method.

Anyway, Just update to V1.0.1 and the problem will be fixed. I'm closing the ticket now, but if you still have problem about this, do re-Open the issue. Thanks.

**Closed by myflashlab** 2016-06-07 08:06 UTC

**Comment by Gamezhero** [comment] 2016-06-07 08:34
```
				AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP,             handlerOk);
				AdMob.api.addEventListener(AdMobEvents.AD_CLOSED,               handlerOk);

```

I init new Interstitoal ads on this event not after.

**Comment by myflashlab** [comment] 2016-06-07 08:50
ok, glad to hear that. Just one note for you to better manage this in your app. It's a good idea to initialize the interstitial ad, only once in your app. call ```loadAd``` whenever you need to load a new ad but you don't have to dispose and then re-init it again.

**Comment by Gamezhero** [comment] 2016-06-07 08:53
Yes, I init ones and load new interstitial after close ad or left app (click on ad)

```
public function initNewInterstitialBanner():void
		{
			if (isSupport())
			{
				try
				{
					var adRequest:AdRequest = new AdRequest();
					AdMob.api.interstitial.loadAd(adRequest);
				}
				catch(e:Error){}
			}
		}
```

**Comment by BAAKILI1987** [comment] 2018-11-21 14:43
What does mean that ?

 This ANE will not work unless you have added the other dependency ANEs
or .frameworks to your project also. Please read the setup information
 and also check out the sample project on our repository to know what
 are the requirements for this ANE to work as expected

  how can i add other dependency ANEs  or frameworks ? :


 and when i impliment and writing the code in first frame timeline (Animate CC)  does not debug and i make Error  :

 ReferenceError: Error #1065: Variable OverrideAir is not defined.

sometimes ; 
 ReferenceError: Error #1065: Variable onAdClosed is not defined.

 help me please !
 thanks

**Comment by myflashlab** [comment] 2018-11-21 14:47
@BAAKILI1987  https://github.com/myflashlab/Admob-ANE/wiki/A.-Preparing-the-Adobe-Air-side
