### ISSUE TITLE
[ios] Error creating files

### ISSUE THREAD

**Issue by flashawy** [myflashlab/Admob-ANE#19] opened 2017-03-18 08:18 UTC
Hi,

while the ANE worked with me flawlessly for the Android version. I get A wierd error with the ios version of my app.

check this screenshot for the error I get 
![admobiosproblem](https://cloud.githubusercontent.com/assets/62462/24070320/c6c1e142-0bc3-11e7-8e62-bc0642ac7050.png)

- I am using AIR SDK 24
- I have Included the dependencies required for this ANE
- I also added the GoogleMobileAds.framwork and others mentioned in latest changelog
- I am using Animate CC 2015.1 on a Windows7 

so what could be the problem?

**Comment by myflashlab** [comment] 2017-03-18 08:21
The latest version of the ANE on the iOS is dependent on the OverrideAIR ANE, [read here](https://github.com/myflashlab/Admob-ANE#changelog)

**Comment by myflashlab** [comment] 2017-03-19 05:29
Let us know if the problem is fixed? should we close the issue?

**Comment by myflashlab** [comment] 2018-12-14 14:57
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).

**Closed by myflashlab** 2018-12-14 14:57 UTC
