### ISSUE TITLE
Nothing showing on Android

### ISSUE THREAD

**Issue by misterPitty** [myflashlab/Admob-ANE#21] opened 2017-04-19 13:25 UTC
Hi. I use this ane in my Android project. This is my third ane from your team so i am sure i include it correctly.
Ane successfuly init but i have nothing on the stage, when it loads ad. No one listeners don't work too.
My app not available in gplay yet but i used _adRequest.testDevices()_ to add my phone as testing device.
What else could it be?

**Comment by myflashlab** [comment] 2017-04-20 06:16
The first thing to check is that if you are using the latest dependency files? https://github.com/myflashlab/Admob-ANE#requirements

then, double check if you have set the manifest .xml file correctly?

also check if you have set your testDevices correctly? https://github.com/myflashlab/Admob-ANE/blob/master/FD/src/Demo.as#L202-L208

**Comment by misterPitty** [comment] 2017-04-20 07:47
Thank for answer. Seems like i use wrong device ID. Can i get correct id without using Android Studio?
I used some apps and got ID but it includes 16 symbols not 32. Maybe full ID consist from devise ID + GSF. Or not?

**Comment by myflashlab** [comment] 2017-04-20 08:05
> Can i get correct id without using Android Studio?

I really don't know! we used Android Studio and the docs also suggested to use Android Studio. Happy to see the problem is now fixed anyway. :)

**Closed by myflashlab** 2017-04-20 08:05 UTC
